export type TradeHistoryEntry = {
	uid: string;
	txId?: string;
	createdAt: number;
	updatedAt: number;
	strategyName?: string;
	status: "success" | "error" | "fetchingResult" | "pending" | "unknown";
	inTokenSymbol?: string;
	inTokenDecimals?: number;
	outTokenSymbol?: string;
	outTokenDecimals?: number;
	inTokenAddress?: string;
	outTokenAddress?: string;
	inAmount?: number;
	outAmount?: number;
	inUiAmount?: number;
	outUiAmount?: number;
	price?: number;
	profit?: number;
	profitPercent?: number;
	unrealizedProfit?: number;
	unrealizedProfitPercent?: number;
	expectedPrice?: number;
	expectedOutAmount?: number;
	expectedProfit?: number;
	expectedProfitPercent?: number;
	slippage?: number;
	error?: string;
	arbAccTxId?: string;
	arbAccRuntimeId?: string;
	arbAccAmount?: number;
	isArbAccTx?: boolean;
};
