const ARB_PROTOCOL = Object.freeze({
	PUBLIC_KEY: "9tzZzEHsKnwFL1A3DyFJwj36KnZj3gZ7g4srWp9YTEoh",
	FEE_ACCOUNT_PUBLIC_KEY: "HZv4NzXpX2FCqCWNY7X2rF3E6YnnxQ7qSrPXUMZ2mu9R",
	REQUIRED_AMOUNT: 10_000,
});

module.exports = ARB_PROTOCOL;
